name: EngCalc
description: A calculator made by engineers for engineers.
# version: 0.4
#homepage: https://www.example.com
#author: Jack0fAll <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
